IF NOT EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'DocumentProcessingQueue' AND TABLE_SCHEMA = N'labs') 
BEGIN
	CREATE TABLE [labs].[DocumentProcessingQueue](
		[ID] [int] IDENTITY(1,1) NOT NULL,
		[WorkspaceID] [int] NOT NULL,
		[DocumentID] [int] NOT NULL,
		[Status] [int] NOT NULL,
	 CONSTRAINT [PK_DocumentProcessingQueue] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END